version: "3.8"

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: "db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5431:5432"
#  app:
#    build: build/libs
#    environment:
#      DB_PORT: 5431
#      DB_NAME: db
#      DB_USER: postgres
#      DB_PASSWORD: postgres
#    ports:
#      - "8080:8080"
#    depends_on:
#      - postgres